-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE category (
id INT NOT NULL AUTO_INCREMENT SET AS PRIMARY KEY,
category_name STRING NOT NULL
);



CREATE TABLE product(
    id INT NOT NULL AUTO_INCREMENT SET AS PRIMARY KEY,
    product_name STRING NOT NULL,
    price DECIMAL (10,2) NOT NULL,
    stock INT NOT NULL,
    category_id INT,
    FOREIGN KEY (category_id),
    REFERENCES  
)

CREATE TABLE tag

CREATE TABLE productTag